/*
 ***********************************************************************************************************************
 *
 * COPYRIGHT RESERVED, ETAS GmbH, 2021. All rights reserved.
 * The reproduction, distribution and utilization of this document as well as the communication of its contents to
 * others without explicit authorization is prohibited. Offenders will be held liable for the payment of damages.
 * All rights reserved in the event of the grant of a patent, utility model or design.
 *
 ***********************************************************************************************************************
 ************************************************************************************************
 * Component : Rtm.c
 * Date      : Dec 29, 2022
 * Version   : 2.0
 * Description  : This module implements Rtm functions.
 *                Note: This file contains sample implementation only. It is not part of the
 *                      production deliverables. 
 ***********************************************************************************************
*/

/*! \file
 *
 * \brief Runtime measurement hardware independent part
 *
 * This file contains the hardware independent main functions of Rtm.
 *
 * - Initializing at startup of ECU pre StartOS
 * - Initializing at startup of ECU after StartOS (init process)
 * - MainFunction
 * - API
 *
 */

/*
 ***********************************************************************************************************************
 * Includes
 ***********************************************************************************************************************
 */

#include "Rtm_Prv.h"
#include "Rtm_Driver_Prv.h"
#include "Rte_Rtm.h" /* Intended crossscheck of the fn prototypes are identical between for BSW and ASW/SWC for some modules
                        acc. to AUTOSAR if this file is not generated by the Rte, please use the template provided */
#include "EcuM.h"

/*
 ***********************************************************************************************************************
 * Prototypes of local functions only used here
 ***********************************************************************************************************************
 */

/*
 ***********************************************************************************************************************
 * Variable definition
 ***********************************************************************************************************************
 */

/*
 ***********************************************************************************************************************
 * Code
 ***********************************************************************************************************************
 */

#define RTM_START_SEC_CODE_SLOW
#include "Rtm_MemMap.h"

/** Rtm_PreOSInit ******************************************************************************************/
/*!
 * \brief       Initializing function
 *
 * \param       void
 * \return      void
 *
 * Must be called at startup before start os from Master or startup core.
 */
FUNC (void, RTM_CODE_SLOW) Rtm_PreOSInit (void)
{
    CoreIdType coreId;
    /* Get core ID */
    coreId = Rtm_GetLogicalCoreID();
    /* Init only on Master core or EcuM Startup core. */
    if ((OS_CORE_ID_MASTER == coreId) || (ECUM_CFG_STARTUP_CORE == coreId))
    {
        /* Init submodules */
        Rtm_Mon_Init();
    }
#if (RTM_CTRL == STD_ON)
    /* Init driver submodule */
    Rtm_Driver_PreOSInit();
#endif
}

/** Rtm_Init ******************************************************************************************/
/*!
 * \brief       Initializing function
 *
 * \param       void
 * \return      void
 *
 * Must be called at startup before the first task ends on each core
 */
FUNC (void, RTM_CODE_SLOW) Rtm_Init (void)
{
    /* Init MT submodule */
    Rtm_MT_Init();
    /* Init ctrl submodule */
#if (RTM_CTRL == STD_ON)
    Rtm_Ctrl_Init();
#endif
}
#define RTM_STOP_SEC_CODE_SLOW
#include "Rtm_MemMap.h"

#define RTM_START_SEC_CODE
#include "Rtm_MemMap.h"

/** Rtm_MainFunction ******************************************************************************************/
/*!
 * \brief       Main function for master core
 *
 * \param       void
 * \return      void
 *
 * Main function called periodical from a task
 */
FUNC (void, RTM_CODE) Rtm_MainFunction (void)
{
#ifdef RTM_DEBUG
    /* Empty function for tests */
    Rtm_EmptyFunc();
#endif
    /* Call main function of submodule monitor */
    Rtm_Mon_MainFunction ();
    
#if (RTM_CTRL == STD_ON)
    /* Call main function of submodule control */
    Rtm_Ctrl_MainFunction ();
#endif
}

/** Rtm_EmptyFunc **********************************************************************************************/
/*!
 * \brief       Empty function to calibrate the runtime measurement
 *
 * \param       void
 * \return      void
 *
 * This function is used to calibrate the measurements
 */
FUNC (void, RTM_CODE) Rtm_EmptyFunc(void)
{
    RTM_NOP();
}

#ifdef RTM_DEBUG
/** Rtm_Assert ************************************************************************************************/
/*!
 * \brief       Assert handler for Rtm
 *
 * \param       void
 * \return      void
 *
 * This is called whenever a unexpected behaviour is detected. It is only used if test/debug mode is active.
 */
uint32 Rtm_ErrorCnt_u32 = 0;
FUNC (void, RTM_CODE) Rtm_Assert()
{
    Rtm_ErrorCnt_u32++;
}
#endif


/** Rtm_GetSystemLoad *****************************************************************************************/
/*!
 * \brief    Interface to acquire core specific system load information
 *
 * \param    uint8_least  Logical id of core
 * \return   uint16       System load on specific core in 64k:
                          0x0000:      0% system load
                          0xffff: 99.985% system load (0x10000 -> 100%)
 */
FUNC (uint16, RTM_CODE) Rtm_GetSystemLoad (uint8_least coreId)
{
    uint16 ret = 0;
    if (coreId < RTM_NUM_CORES)
    {
        ret = Rtm_MonSystemLoadPer64k_au16[coreId];
    }
    return ret;
}


/** Rtm_GetVersionInfo ****************************************************************************************/
/*!
 * \brief    Get version information including Vendor Id, Module Id and Version Info
 *
 * \param    Std_VersionInfoType*  Pointer to structure Std_VersionInfoType
 * \return   void
 */
#if (RTM_VERSIONINFOAPI == STD_ON)
FUNC (void, RTM_CODE) Rtm_GetVersionInfo(Std_VersionInfoType* versionInfo)
{
    versionInfo->vendorID = RTM_VENDOR_ID;
    versionInfo->moduleID = RTM_MODULE_ID;
    versionInfo->sw_major_version = RTM_SW_MAJOR_VERSION;
    versionInfo->sw_minor_version = RTM_SW_MINOR_VERSION;
    versionInfo->sw_patch_version = RTM_SW_PATCH_VERSION;
}
#endif

#define RTM_STOP_SEC_CODE
#include "Rtm_MemMap.h"

/*
 ***********************************************************************************************************************
 * End of file
 ***********************************************************************************************************************
*/

