/*
 * File: Bsw_MemMap.h
 * Generated by: TAN9SGH
 * Version: ETAS Cobra 2.0
 * on: 2022/12/29 14:29
 * This is a template file. It defines integration functions necessary to complete RTA-BSW.
 * The integrator must complete the templates before deploying software containing functions defined in this file.
 * Once templates have been completed, the integrator should delete the #error line.
 * Note: The integrator is responsible for updates made to this file.
 *
 * To remove the following error define the macro NOT_READY_FOR_TESTING_OR_DEPLOYMENT with a compiler option (e.g. -D NOT_READY_FOR_TESTING_OR_DEPLOYMENT)
 * The removal of the error only allows the user to proceed with the building phase
 */

#ifndef NOT_READY_FOR_TESTING_OR_DEPLOYMENT
//#error The content of this file is a template which provides empty stubs. The content of this file must be completed by the integrator accordingly to project specific requirements
#else
//#warning The content of this file is a template which provides empty stubs. The content of this file must be completed by the integrator accordingly to project specific requirements
#endif /* NOT_READY_FOR_TESTING_OR_DEPLOYMENT */
#if defined (BSW_START_SEC_CODE)
   #undef      BSW_START_SEC_CODE
   #define BSW_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CODE
#elif defined (BSW_STOP_SEC_CODE)
   #undef      BSW_STOP_SEC_CODE
   #define BSW_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (BSW_START_SEC_CODE_FAST)
   #undef      BSW_START_SEC_CODE_FAST
   #define BSW_START_SEC_EcucPartition_SysCore_CODE_FAST
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CODE_FAST
#elif defined (BSW_STOP_SEC_CODE_FAST)
   #undef      BSW_STOP_SEC_CODE_FAST
   #define BSW_STOP_SEC_EcucPartition_SysCore_CODE_FAST
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CODE_FAST
#elif defined (BSW_START_SEC_VAR_CLEARED_8)
   #undef      BSW_START_SEC_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (BSW_START_SEC_VAR_CLEARED_32)
   #undef      BSW_START_SEC_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32
#elif defined (BSW_START_SEC_VAR_INIT_8)
   #undef      BSW_START_SEC_VAR_INIT_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_8
#elif defined (BSW_STOP_SEC_VAR_INIT_8)
   #undef      BSW_STOP_SEC_VAR_INIT_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_8
#elif defined (BSW_START_SEC_VAR_INIT_16)
   #undef      BSW_START_SEC_VAR_INIT_16
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_16
#elif defined (BSW_STOP_SEC_VAR_INIT_16)
   #undef      BSW_STOP_SEC_VAR_INIT_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_16
#elif defined (BSW_START_SEC_VAR_INIT_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_INIT_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_INIT_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_UNSPECIFIED
#elif defined (BSW_START_SEC_CONST_8)
   #undef      BSW_START_SEC_CONST_8
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_8
#elif defined (BSW_STOP_SEC_CONST_8)
   #undef      BSW_STOP_SEC_CONST_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_8
#elif defined (BSW_START_SEC_CONST_16)
   #undef      BSW_START_SEC_CONST_16
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_16
#elif defined (BSW_STOP_SEC_CONST_16)
   #undef      BSW_STOP_SEC_CONST_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_16
#elif defined (BSW_START_SEC_CONST_UNSPECIFIED)
   #undef      BSW_START_SEC_CONST_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CONST_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CONST_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE0_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE0_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE0_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE0_UNSPECIFIED
#elif defined (BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED)
   #undef      BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_CLEARED_POSTBUILD_8)
   #undef      BSW_START_SEC_VAR_CLEARED_POSTBUILD_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_8
#elif defined (BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_8)
   #undef      BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_8
#elif defined (BSW_START_SEC_VAR_CLEARED_POSTBUILD_32)
   #undef      BSW_START_SEC_VAR_CLEARED_POSTBUILD_32
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_32
#elif defined (BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_32)
   #undef      BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_32
#elif defined (BSW_START_SEC_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_FAST_CLEARED_8)
   #undef      BSW_START_SEC_VAR_FAST_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_8
#elif defined (BSW_STOP_SEC_VAR_FAST_CLEARED_8)
   #undef      BSW_STOP_SEC_VAR_FAST_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_8
#elif defined (BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CONFIG_DATA_POSTBUILD_8)
   #undef      BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_8
#elif defined (BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8)
   #undef      BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_8
#elif defined (BSW_START_SEC_VAR_CLEARED_16)
   #undef      BSW_START_SEC_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CONFIG_DATA_POSTBUILD_16)
   #undef      BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_16
#elif defined (BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16)
   #undef      BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_16
#elif defined (BSW_START_SEC_CONFIG_DATA_POSTBUILD_32)
   #undef      BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_32
#elif defined (BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32)
   #undef      BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_POSTBUILD_32
#elif defined (BSW_START_SEC_CONFIG_DATA_UNSPECIFIED)
   #undef      BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_UNSPECIFIED
#elif defined (BSW_START_SEC_DEFAULT_CODE)
   #undef      BSW_START_SEC_DEFAULT_CODE
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CODE
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CODE
#elif defined (BSW_STOP_SEC_DEFAULT_CODE)
   #undef      BSW_STOP_SEC_DEFAULT_CODE
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CODE
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CODE
#elif defined (BSW_START_SEC_VAR_INIT_BOOLEAN)
   #undef      BSW_START_SEC_VAR_INIT_BOOLEAN
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_BOOLEAN
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_BOOLEAN
#elif defined (BSW_STOP_SEC_VAR_INIT_BOOLEAN)
   #undef      BSW_STOP_SEC_VAR_INIT_BOOLEAN
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_BOOLEAN
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_BOOLEAN
#elif defined (BSW_START_SEC_CONST_32)
   #undef      BSW_START_SEC_CONST_32
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_32
#elif defined (BSW_STOP_SEC_CONST_32)
   #undef      BSW_STOP_SEC_CONST_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_32
#elif defined (BSW_START_SEC_VAR_CLEARED_BOOLEAN)
   #undef      BSW_START_SEC_VAR_CLEARED_BOOLEAN
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
#elif defined (BSW_STOP_SEC_VAR_CLEARED_BOOLEAN)
   #undef      BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
#elif defined (BSW_START_SEC_CORE1_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE1_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE1_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE1_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE1_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE1_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE1_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE1_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE1_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE1_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE1_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE1_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE1_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE1_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE1_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE1_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE1_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE1_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE1_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CORE2_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE2_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE2_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE2_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE2_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE2_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE2_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE2_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE2_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE2_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE2_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE2_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE2_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE2_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE2_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE2_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE2_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE2_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE2_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CORE3_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE3_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE3_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE3_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE3_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE3_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE3_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE3_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE3_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE3_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE3_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE3_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE3_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE3_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE3_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE3_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE3_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE3_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE3_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CORE4_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE4_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE4_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE4_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE4_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE4_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE4_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE4_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE4_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE4_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE4_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE4_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE4_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE4_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE4_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE4_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE4_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE4_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE4_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CORE5_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE5_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE5_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE5_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE5_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE5_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE5_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE5_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE5_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE5_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE5_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE5_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE5_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE5_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE5_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE5_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE5_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE5_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE5_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_CORE6_VAR_CLEARED_8)
   #undef      BSW_START_SEC_CORE6_VAR_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_8
#elif defined (BSW_STOP_SEC_CORE6_VAR_CLEARED_8)
   #undef      BSW_STOP_SEC_CORE6_VAR_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_8
#elif defined (BSW_START_SEC_CORE6_VAR_CLEARED_16)
   #undef      BSW_START_SEC_CORE6_VAR_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_16
#elif defined (BSW_STOP_SEC_CORE6_VAR_CLEARED_16)
   #undef      BSW_STOP_SEC_CORE6_VAR_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_16
#elif defined (BSW_START_SEC_CORE6_VAR_CLEARED_32)
   #undef      BSW_START_SEC_CORE6_VAR_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_32
#elif defined (BSW_STOP_SEC_CORE6_VAR_CLEARED_32)
   #undef      BSW_STOP_SEC_CORE6_VAR_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_32
#elif defined (BSW_START_SEC_CORE6_VAR_CLEARED_64)
   #undef      BSW_START_SEC_CORE6_VAR_CLEARED_64
   #define BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_64
#elif defined (BSW_STOP_SEC_CORE6_VAR_CLEARED_64)
   #undef      BSW_STOP_SEC_CORE6_VAR_CLEARED_64
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_64
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_64
#elif defined (BSW_START_SEC_CORE6_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CORE6_VAR_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CORE6_VAR_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN)
   #undef      BSW_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_BOOLEAN
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_BOOLEAN
#elif defined (BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN)
   #undef      BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_BOOLEAN
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_BOOLEAN
#elif defined (BSW_START_SEC_VAR_CLEARED_POSTBUILD_16)
   #undef      BSW_START_SEC_VAR_CLEARED_POSTBUILD_16
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_16
#elif defined (BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_16)
   #undef      BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_POSTBUILD_16
#elif defined (BSW_START_SEC_CONFIG_DATA_32)
   #undef      BSW_START_SEC_CONFIG_DATA_32
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_32
#elif defined (BSW_STOP_SEC_CONFIG_DATA_32)
   #undef      BSW_STOP_SEC_CONFIG_DATA_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_32
#elif defined (BSW_START_SEC_CONFIG_DATA_16)
   #undef      BSW_START_SEC_CONFIG_DATA_16
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_16
#elif defined (BSW_STOP_SEC_CONFIG_DATA_16)
   #undef      BSW_STOP_SEC_CONFIG_DATA_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_16
#elif defined (BSW_START_SEC_CONFIG_DATA_8)
   #undef      BSW_START_SEC_CONFIG_DATA_8
   #define BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONFIG_DATA_8
#elif defined (BSW_STOP_SEC_CONFIG_DATA_8)
   #undef      BSW_STOP_SEC_CONFIG_DATA_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONFIG_DATA_8
#elif defined (BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED)
   #undef      BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_UNSPECIFIED
#elif defined (BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED)
   #undef      BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_UNSPECIFIED
#elif defined (BSW_START_SEC_DEFAULT_CONST_8)
   #undef      BSW_START_SEC_DEFAULT_CONST_8
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_8
#elif defined (BSW_STOP_SEC_DEFAULT_CONST_8)
   #undef      BSW_STOP_SEC_DEFAULT_CONST_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_8
#elif defined (BSW_START_SEC_DEFAULT_CONST_16)
   #undef      BSW_START_SEC_DEFAULT_CONST_16
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_16
#elif defined (BSW_STOP_SEC_DEFAULT_CONST_16)
   #undef      BSW_STOP_SEC_DEFAULT_CONST_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_16
#elif defined (BSW_START_SEC_DEFAULT_CONST_32)
   #undef      BSW_START_SEC_DEFAULT_CONST_32
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_CONST_32
#elif defined (BSW_STOP_SEC_DEFAULT_CONST_32)
   #undef      BSW_STOP_SEC_DEFAULT_CONST_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_CONST_32
#elif defined (BSW_START_SEC_DEFAULT_RAM0_INIT_8)
   #undef      BSW_START_SEC_DEFAULT_RAM0_INIT_8
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_8
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_INIT_8)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_8
#elif defined (BSW_START_SEC_DEFAULT_RAM0_INIT_16)
   #undef      BSW_START_SEC_DEFAULT_RAM0_INIT_16
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_16
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_INIT_16)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_16
#elif defined (BSW_START_SEC_DEFAULT_RAM0_INIT_32)
   #undef      BSW_START_SEC_DEFAULT_RAM0_INIT_32
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_32
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_INIT_32)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_32
#elif defined (BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED)
   #undef      BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_UNSPECIFIED
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_INIT_UNSPECIFIED
#elif defined (BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED)
   #undef      BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_UNSPECIFIED
#elif defined (BSW_START_SEC_DEFAULT_RAM0_CLEARED_8)
   #undef      BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_8
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_8
#elif defined (BSW_START_SEC_DEFAULT_RAM0_CLEARED_16)
   #undef      BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_16
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_16
#elif defined (BSW_START_SEC_DEFAULT_RAM0_CLEARED_32)
   #undef      BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_32
#elif defined (BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32)
   #undef      BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RAM0_CLEARED_32
#elif defined (BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_SAVED_ZONE_UNSPECIFIED
#elif defined (BSW_START_SEC_SAVED_ZONE_8)
   #undef      BSW_START_SEC_SAVED_ZONE_8
   #define BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_8
#elif defined (BSW_STOP_SEC_SAVED_ZONE_8)
   #undef      BSW_STOP_SEC_SAVED_ZONE_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_8
#elif defined (BSW_START_SEC_SAVED_ZONE_UNSPECIFIED)
   #undef      BSW_START_SEC_SAVED_ZONE_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_UNSPECIFIED
#elif defined (BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED)
   #undef      BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_INIT_32)
   #undef      BSW_START_SEC_VAR_INIT_32
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_INIT_32
#elif defined (BSW_STOP_SEC_VAR_INIT_32)
   #undef      BSW_STOP_SEC_VAR_INIT_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_INIT_32
#elif defined (BSW_START_SEC_VAR_CLEARED_SECURED_32)
   #undef      BSW_START_SEC_VAR_CLEARED_SECURED_32
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_32
#elif defined (BSW_STOP_SEC_VAR_CLEARED_SECURED_32)
   #undef      BSW_STOP_SEC_VAR_CLEARED_SECURED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_32
#elif defined (BSW_START_SEC_VAR_CLEARED_SECURED_8)
   #undef      BSW_START_SEC_VAR_CLEARED_SECURED_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_8
#elif defined (BSW_STOP_SEC_VAR_CLEARED_SECURED_8)
   #undef      BSW_STOP_SEC_VAR_CLEARED_SECURED_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_8
#elif defined (BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_UNSPECIFIED
#elif defined (BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED)
   #undef      BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
#elif defined (BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED)
   #undef      BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
#elif defined (BSW_START_SEC_SAVED_ZONE_16)
   #undef      BSW_START_SEC_SAVED_ZONE_16
   #define BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_16
#elif defined (BSW_STOP_SEC_SAVED_ZONE_16)
   #undef      BSW_STOP_SEC_SAVED_ZONE_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_16
#elif defined (BSW_START_SEC_SAVED_ZONE_32)
   #undef      BSW_START_SEC_SAVED_ZONE_32
   #define BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_SAVED_ZONE_32
#elif defined (BSW_STOP_SEC_SAVED_ZONE_32)
   #undef      BSW_STOP_SEC_SAVED_ZONE_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_SAVED_ZONE_32
#elif defined (BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_8)
   #undef      BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_8
#elif defined (BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8)
   #undef      BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_8
#elif defined (BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_16)
   #undef      BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_16
#elif defined (BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16)
   #undef      BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_16
#elif defined (BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_32)
   #undef      BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_32
#elif defined (BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32)
   #undef      BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_32
#elif defined (BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED)
   #undef      BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#elif defined (BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED)
   #undef      BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#elif defined (BSW_START_SEC_CONST_BOOLEAN)
   #undef      BSW_START_SEC_CONST_BOOLEAN
   #define BSW_START_SEC_EcucPartition_SysCore_CONST_BOOLEAN
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_CONST_BOOLEAN
#elif defined (BSW_STOP_SEC_CONST_BOOLEAN)
   #undef      BSW_STOP_SEC_CONST_BOOLEAN
   #define BSW_STOP_SEC_EcucPartition_SysCore_CONST_BOOLEAN
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_CONST_BOOLEAN
#elif defined (BSW_START_SEC_VAR_FAST_CLEARED_16)
   #undef      BSW_START_SEC_VAR_FAST_CLEARED_16
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_16
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_16
#elif defined (BSW_STOP_SEC_VAR_FAST_CLEARED_16)
   #undef      BSW_STOP_SEC_VAR_FAST_CLEARED_16
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_16
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_CLEARED_16
#elif defined (BSW_START_SEC_VAR_FAST_INIT_8)
   #undef      BSW_START_SEC_VAR_FAST_INIT_8
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_INIT_8
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_FAST_INIT_8
#elif defined (BSW_STOP_SEC_VAR_FAST_INIT_8)
   #undef      BSW_STOP_SEC_VAR_FAST_INIT_8
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_INIT_8
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_FAST_INIT_8
#elif defined (BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32)
   #undef      BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_32
#elif defined (BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32)
   #undef      BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_32
#elif defined (BSW_START_SEC_VAR_ED_POWER_ON_CLEARED_32)
   #undef      BSW_START_SEC_VAR_ED_POWER_ON_CLEARED_32
   #define BSW_START_SEC_EcucPartition_SysCore_VAR_ED_POWER_ON_CLEARED_32
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_VAR_ED_POWER_ON_CLEARED_32
#elif defined (BSW_STOP_SEC_VAR_ED_POWER_ON_CLEARED_32)
   #undef      BSW_STOP_SEC_VAR_ED_POWER_ON_CLEARED_32
   #define BSW_STOP_SEC_EcucPartition_SysCore_VAR_ED_POWER_ON_CLEARED_32
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_VAR_ED_POWER_ON_CLEARED_32
#elif defined (BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED)
   #undef      BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
   #define BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
#elif defined (BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED)
   #undef      BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
   #define BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
#elif defined (BSW_START_SEC_SPRAM_CODE)
   #undef      BSW_START_SEC_SPRAM_CODE
   #define BSW_START_SEC_EcucPartition_SysCore_SPRAM_CODE
   #include "MemMap.h"
   #undef BSW_START_SEC_EcucPartition_SysCore_SPRAM_CODE
#elif defined (BSW_STOP_SEC_SPRAM_CODE)
   #undef      BSW_STOP_SEC_SPRAM_CODE
   #define BSW_STOP_SEC_EcucPartition_SysCore_SPRAM_CODE
   #include "MemMap.h"
   #undef BSW_STOP_SEC_EcucPartition_SysCore_SPRAM_CODE
#else
    #error "Bsw_MemMap.h, memmap section unconfigured"
#endif


/*
 **********************************************************************************************************************
 * End of the file
 **********************************************************************************************************************
 */
