/*
 * File: CalUT_MemMap.h
 * Generated by: TAN9SGH
 * Version: ETAS Cobra 2.0
 * on: 2022/12/29 14:29
*/


#if defined (START_WITH_IF)
#elif defined CalUT_START_SEC_SHAREDMEMORY_BOOLEAN
   #undef CalUT_START_SEC_SHAREDMEMORY_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_SHAREDMEMORY_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SHAREDMEMORY_BOOLEAN
   #undef CalUT_STOP_SEC_SHAREDMEMORY_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_SHAREDMEMORY_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SHAREDMEMORY_8
   #undef CalUT_START_SEC_SHAREDMEMORY_8
   #define ASW_START_SEC_EcucPartition_AppCore_SHAREDMEMORY_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SHAREDMEMORY_8
   #undef CalUT_STOP_SEC_SHAREDMEMORY_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_SHAREDMEMORY_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SHAREDMEMORY_16
   #undef CalUT_START_SEC_SHAREDMEMORY_16
   #define ASW_START_SEC_EcucPartition_AppCore_SHAREDMEMORY_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SHAREDMEMORY_16
   #undef CalUT_STOP_SEC_SHAREDMEMORY_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_SHAREDMEMORY_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SHAREDMEMORY_32
   #undef CalUT_START_SEC_SHAREDMEMORY_32
   #define ASW_START_SEC_EcucPartition_AppCore_SHAREDMEMORY_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SHAREDMEMORY_32
   #undef CalUT_STOP_SEC_SHAREDMEMORY_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_SHAREDMEMORY_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SHAREDMEMORY_UNSPECIFIED
   #undef CalUT_START_SEC_SHAREDMEMORY_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_SHAREDMEMORY_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SHAREDMEMORY_UNSPECIFIED
   #undef CalUT_STOP_SEC_SHAREDMEMORY_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_SHAREDMEMORY_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_NO_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_NO_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_NO_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_NO_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_NO_INIT_8
   #undef CalUT_START_SEC_VAR_NO_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_NO_INIT_8
   #undef CalUT_STOP_SEC_VAR_NO_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_NO_INIT_16
   #undef CalUT_START_SEC_VAR_NO_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_NO_INIT_16
   #undef CalUT_STOP_SEC_VAR_NO_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_NO_INIT_32
   #undef CalUT_START_SEC_VAR_NO_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_NO_INIT_32
   #undef CalUT_STOP_SEC_VAR_NO_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_NO_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_8
   #undef CalUT_START_SEC_VAR_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_16
   #undef CalUT_START_SEC_VAR_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_32
   #undef CalUT_START_SEC_VAR_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_CLEARED_8
   #undef CalUT_START_SEC_VAR_POWER_ON_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_CLEARED_16
   #undef CalUT_START_SEC_VAR_POWER_ON_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_CLEARED_32
   #undef CalUT_START_SEC_VAR_POWER_ON_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_INIT_8
   #undef CalUT_START_SEC_VAR_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_INIT_8
   #undef CalUT_STOP_SEC_VAR_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_INIT_16
   #undef CalUT_START_SEC_VAR_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_INIT_16
   #undef CalUT_STOP_SEC_VAR_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_INIT_32
   #undef CalUT_START_SEC_VAR_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_INIT_32
   #undef CalUT_STOP_SEC_VAR_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_INIT_8
   #undef CalUT_START_SEC_VAR_POWER_ON_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_INIT_8
   #undef CalUT_STOP_SEC_VAR_POWER_ON_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_INIT_16
   #undef CalUT_START_SEC_VAR_POWER_ON_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_INIT_16
   #undef CalUT_STOP_SEC_VAR_POWER_ON_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_INIT_32
   #undef CalUT_START_SEC_VAR_POWER_ON_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_INIT_32
   #undef CalUT_STOP_SEC_VAR_POWER_ON_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #undef CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_8
   #undef CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_8
   #undef CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_16
   #undef CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_16
   #undef CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_32
   #undef CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_32
   #undef CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SAVED_ZONE_BOOLEAN
   #undef CalUT_START_SEC_VAR_SAVED_ZONE_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SAVED_ZONE_8
   #undef CalUT_START_SEC_VAR_SAVED_ZONE_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SAVED_ZONE_8
   #undef CalUT_STOP_SEC_VAR_SAVED_ZONE_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SAVED_ZONE_16
   #undef CalUT_START_SEC_VAR_SAVED_ZONE_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SAVED_ZONE_16
   #undef CalUT_STOP_SEC_VAR_SAVED_ZONE_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SAVED_ZONE_32
   #undef CalUT_START_SEC_VAR_SAVED_ZONE_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SAVED_ZONE_32
   #undef CalUT_STOP_SEC_VAR_SAVED_ZONE_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_BOOLEAN
   #undef CalUT_START_SEC_CONST_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_BOOLEAN
   #undef CalUT_STOP_SEC_CONST_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_8
   #undef CalUT_START_SEC_CONST_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_8
   #undef CalUT_STOP_SEC_CONST_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_16
   #undef CalUT_START_SEC_CONST_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_16
   #undef CalUT_STOP_SEC_CONST_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_32
   #undef CalUT_START_SEC_CONST_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_32
   #undef CalUT_STOP_SEC_CONST_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_UNSPECIFIED
   #undef CalUT_START_SEC_CONST_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONST_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_BOOLEAN
   #undef CalUT_START_SEC_CONFIG_DATA_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_BOOLEAN
   #undef CalUT_STOP_SEC_CONFIG_DATA_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_8
   #undef CalUT_START_SEC_CONFIG_DATA_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_8
   #undef CalUT_STOP_SEC_CONFIG_DATA_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_16
   #undef CalUT_START_SEC_CONFIG_DATA_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_16
   #undef CalUT_STOP_SEC_CONFIG_DATA_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_32
   #undef CalUT_START_SEC_CONFIG_DATA_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_32
   #undef CalUT_STOP_SEC_CONFIG_DATA_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_UNSPECIFIED
   #undef CalUT_START_SEC_CONFIG_DATA_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONFIG_DATA_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_CONST_BOOLEAN
   #undef CalUT_START_SEC_POSTBUILD_CONST_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_CONST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_CONST_BOOLEAN
   #undef CalUT_STOP_SEC_POSTBUILD_CONST_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_CONST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_CONST_8
   #undef CalUT_START_SEC_POSTBUILD_CONST_8
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_CONST_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_CONST_8
   #undef CalUT_STOP_SEC_POSTBUILD_CONST_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_CONST_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_CONST_16
   #undef CalUT_START_SEC_POSTBUILD_CONST_16
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_CONST_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_CONST_16
   #undef CalUT_STOP_SEC_POSTBUILD_CONST_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_CONST_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_CONST_32
   #undef CalUT_START_SEC_POSTBUILD_CONST_32
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_CONST_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_CONST_32
   #undef CalUT_STOP_SEC_POSTBUILD_CONST_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_CONST_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_POSTBUILD_CONST_UNSPECIFIED
   #undef CalUT_START_SEC_POSTBUILD_CONST_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_POSTBUILD_CONST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
   #undef CalUT_STOP_SEC_POSTBUILD_CONST_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_POSTBUILD_CONST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_BOOLEAN
   #undef CalUT_START_SEC_CALIB_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_BOOLEAN
   #undef CalUT_STOP_SEC_CALIB_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_8
   #undef CalUT_START_SEC_CALIB_8
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_8
   #undef CalUT_STOP_SEC_CALIB_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_16
   #undef CalUT_START_SEC_CALIB_16
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_16
   #undef CalUT_STOP_SEC_CALIB_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_32
   #undef CalUT_START_SEC_CALIB_32
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_32
   #undef CalUT_STOP_SEC_CALIB_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_UNSPECIFIED
   #undef CalUT_START_SEC_CALIB_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_UNSPECIFIED
   #undef CalUT_STOP_SEC_CALIB_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CODE
   #undef CalUT_START_SEC_CODE
   #define ASW_START_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CODE
   #undef CalUT_STOP_SEC_CODE
   #define ASW_STOP_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALLOUT_CODE
   #undef CalUT_START_SEC_CALLOUT_CODE
   #define ASW_START_SEC_EcucPartition_AppCore_CALLOUT_CODE
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALLOUT_CODE
   #undef CalUT_STOP_SEC_CALLOUT_CODE
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALLOUT_CODE
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALPRM_BOOLEAN
   #undef CalUT_START_SEC_CALPRM_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CALPRM_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALPRM_BOOLEAN
   #undef CalUT_STOP_SEC_CALPRM_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALPRM_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALPRM_8
   #undef CalUT_START_SEC_CALPRM_8
   #define ASW_START_SEC_EcucPartition_AppCore_CALPRM_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALPRM_8
   #undef CalUT_STOP_SEC_CALPRM_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALPRM_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALPRM_16
   #undef CalUT_START_SEC_CALPRM_16
   #define ASW_START_SEC_EcucPartition_AppCore_CALPRM_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALPRM_16
   #undef CalUT_STOP_SEC_CALPRM_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALPRM_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALPRM_32
   #undef CalUT_START_SEC_CALPRM_32
   #define ASW_START_SEC_EcucPartition_AppCore_CALPRM_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALPRM_32
   #undef CalUT_STOP_SEC_CALPRM_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALPRM_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALPRM_UNSPECIFIED
   #undef CalUT_START_SEC_CALPRM_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CALPRM_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALPRM_UNSPECIFIED
   #undef CalUT_STOP_SEC_CALPRM_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALPRM_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CODE_FAST
   #undef CalUT_START_SEC_CODE_FAST
   #define ASW_START_SEC_EcucPartition_AppCore_CODE_FAST
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CODE_FAST
   #undef CalUT_STOP_SEC_CODE_FAST
   #define ASW_STOP_SEC_EcucPartition_AppCore_CODE_FAST
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CODE_SLOW
   #undef CalUT_START_SEC_CODE_SLOW
   #define ASW_START_SEC_EcucPartition_AppCore_CODE_SLOW
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CODE_SLOW
   #undef CalUT_STOP_SEC_CODE_SLOW
   #define ASW_STOP_SEC_EcucPartition_AppCore_CODE_SLOW
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SAVED_ZONE_BOOLEAN
   #undef CalUT_START_SEC_SAVED_ZONE_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_SAVED_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SAVED_ZONE_BOOLEAN
   #undef CalUT_STOP_SEC_SAVED_ZONE_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_SAVED_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SAVED_ZONE_8
   #undef CalUT_START_SEC_SAVED_ZONE_8
   #define ASW_START_SEC_EcucPartition_AppCore_SAVED_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SAVED_ZONE_8
   #undef CalUT_STOP_SEC_SAVED_ZONE_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_SAVED_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SAVED_ZONE_16
   #undef CalUT_START_SEC_SAVED_ZONE_16
   #define ASW_START_SEC_EcucPartition_AppCore_SAVED_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SAVED_ZONE_16
   #undef CalUT_STOP_SEC_SAVED_ZONE_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_SAVED_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SAVED_ZONE_32
   #undef CalUT_START_SEC_SAVED_ZONE_32
   #define ASW_START_SEC_EcucPartition_AppCore_SAVED_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SAVED_ZONE_32
   #undef CalUT_STOP_SEC_SAVED_ZONE_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_SAVED_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_SAVED_ZONE_UNSPECIFIED
   #undef CalUT_START_SEC_SAVED_ZONE_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_SAVED_ZONE_UNSPECIFIED
   #undef CalUT_STOP_SEC_SAVED_ZONE_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_SAVED_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_RESET_SAFE_RAM0_BOOLEAN
   #undef CalUT_START_SEC_RESET_SAFE_RAM0_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_RESET_SAFE_RAM0_BOOLEAN
   #undef CalUT_STOP_SEC_RESET_SAFE_RAM0_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_RESET_SAFE_RAM0_8
   #undef CalUT_START_SEC_RESET_SAFE_RAM0_8
   #define ASW_START_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_RESET_SAFE_RAM0_8
   #undef CalUT_STOP_SEC_RESET_SAFE_RAM0_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_RESET_SAFE_RAM0_16
   #undef CalUT_START_SEC_RESET_SAFE_RAM0_16
   #define ASW_START_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_RESET_SAFE_RAM0_16
   #undef CalUT_STOP_SEC_RESET_SAFE_RAM0_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_RESET_SAFE_RAM0_32
   #undef CalUT_START_SEC_RESET_SAFE_RAM0_32
   #define ASW_START_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_RESET_SAFE_RAM0_32
   #undef CalUT_STOP_SEC_RESET_SAFE_RAM0_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_RESET_SAFE_RAM0_UNSPECIFIED
   #undef CalUT_START_SEC_RESET_SAFE_RAM0_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_RESET_SAFE_RAM0_UNSPECIFIED
   #undef CalUT_STOP_SEC_RESET_SAFE_RAM0_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_RESET_SAFE_RAM0_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_SLOW_NO_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SLOW_NO_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_NO_INIT_8
   #undef CalUT_START_SEC_VAR_SLOW_NO_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_NO_INIT_8
   #undef CalUT_STOP_SEC_VAR_SLOW_NO_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_NO_INIT_16
   #undef CalUT_START_SEC_VAR_SLOW_NO_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_NO_INIT_16
   #undef CalUT_STOP_SEC_VAR_SLOW_NO_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_NO_INIT_32
   #undef CalUT_START_SEC_VAR_SLOW_NO_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_NO_INIT_32
   #undef CalUT_STOP_SEC_VAR_SLOW_NO_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SLOW_NO_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VECTORS
   #undef CalUT_START_SEC_VECTORS
   #define ASW_START_SEC_EcucPartition_AppCore_VECTORS
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VECTORS
   #undef CalUT_STOP_SEC_VECTORS
   #define ASW_STOP_SEC_EcucPartition_AppCore_VECTORS
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_FAST_NO_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_FAST_NO_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_NO_INIT_8
   #undef CalUT_START_SEC_VAR_FAST_NO_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_NO_INIT_8
   #undef CalUT_STOP_SEC_VAR_FAST_NO_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_NO_INIT_16
   #undef CalUT_START_SEC_VAR_FAST_NO_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_NO_INIT_16
   #undef CalUT_STOP_SEC_VAR_FAST_NO_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_NO_INIT_32
   #undef CalUT_START_SEC_VAR_FAST_NO_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_NO_INIT_32
   #undef CalUT_STOP_SEC_VAR_FAST_NO_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_FAST_NO_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_TRACE_BOOLEAN
   #undef CalUT_START_SEC_VAR_TRACE_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_TRACE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_TRACE_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_TRACE_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_TRACE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_TRACE_8
   #undef CalUT_START_SEC_VAR_TRACE_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_TRACE_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_TRACE_8
   #undef CalUT_STOP_SEC_VAR_TRACE_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_TRACE_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_TRACE_16
   #undef CalUT_START_SEC_VAR_TRACE_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_TRACE_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_TRACE_16
   #undef CalUT_STOP_SEC_VAR_TRACE_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_TRACE_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_TRACE_32
   #undef CalUT_START_SEC_VAR_TRACE_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_TRACE_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_TRACE_32
   #undef CalUT_STOP_SEC_VAR_TRACE_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_TRACE_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_TRACE_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_TRACE_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_TRACE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_TRACE_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_TRACE_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_TRACE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_8
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_16
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_32
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_8
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_16
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_32
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
   #undef CalUT_START_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_NO_INIT_8
   #undef CalUT_START_SEC_INTERNAL_VAR_NO_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_8
   #undef CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_NO_INIT_16
   #undef CalUT_START_SEC_INTERNAL_VAR_NO_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_16
   #undef CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_NO_INIT_32
   #undef CalUT_START_SEC_INTERNAL_VAR_NO_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_32
   #undef CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_NO_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
   #undef CalUT_START_SEC_INTERNAL_VAR_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_INTERNAL_VAR_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_INIT_8
   #undef CalUT_START_SEC_INTERNAL_VAR_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_INIT_8
   #undef CalUT_STOP_SEC_INTERNAL_VAR_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_INIT_16
   #undef CalUT_START_SEC_INTERNAL_VAR_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_INIT_16
   #undef CalUT_STOP_SEC_INTERNAL_VAR_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_INIT_32
   #undef CalUT_START_SEC_INTERNAL_VAR_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_INIT_32
   #undef CalUT_STOP_SEC_INTERNAL_VAR_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_INTERNAL_VAR_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_CLEARED_8
   #undef CalUT_START_SEC_INTERNAL_VAR_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_8
   #undef CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_CLEARED_16
   #undef CalUT_START_SEC_INTERNAL_VAR_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_16
   #undef CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_CLEARED_32
   #undef CalUT_START_SEC_INTERNAL_VAR_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_32
   #undef CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_INTERNAL_VAR_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_FAST_BOOLEAN
   #undef CalUT_START_SEC_CALIB_FAST_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_FAST_BOOLEAN
   #undef CalUT_STOP_SEC_CALIB_FAST_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_FAST_8
   #undef CalUT_START_SEC_CALIB_FAST_8
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_FAST_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_FAST_8
   #undef CalUT_STOP_SEC_CALIB_FAST_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_FAST_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_FAST_16
   #undef CalUT_START_SEC_CALIB_FAST_16
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_FAST_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_FAST_16
   #undef CalUT_STOP_SEC_CALIB_FAST_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_FAST_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_FAST_32
   #undef CalUT_START_SEC_CALIB_FAST_32
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_FAST_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_FAST_32
   #undef CalUT_STOP_SEC_CALIB_FAST_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_FAST_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_FAST_UNSPECIFIED
   #undef CalUT_START_SEC_CALIB_FAST_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_FAST_UNSPECIFIED
   #undef CalUT_STOP_SEC_CALIB_FAST_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_SLOW_BOOLEAN
   #undef CalUT_START_SEC_CALIB_SLOW_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_SLOW_BOOLEAN
   #undef CalUT_STOP_SEC_CALIB_SLOW_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_SLOW_8
   #undef CalUT_START_SEC_CALIB_SLOW_8
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_SLOW_8
   #undef CalUT_STOP_SEC_CALIB_SLOW_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_SLOW_16
   #undef CalUT_START_SEC_CALIB_SLOW_16
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_SLOW_16
   #undef CalUT_STOP_SEC_CALIB_SLOW_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_SLOW_32
   #undef CalUT_START_SEC_CALIB_SLOW_32
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_SLOW_32
   #undef CalUT_STOP_SEC_CALIB_SLOW_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CALIB_SLOW_UNSPECIFIED
   #undef CalUT_START_SEC_CALIB_SLOW_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CALIB_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CALIB_SLOW_UNSPECIFIED
   #undef CalUT_STOP_SEC_CALIB_SLOW_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CALIB_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_FAST_BOOLEAN
   #undef CalUT_START_SEC_CONFIG_DATA_FAST_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
   #undef CalUT_STOP_SEC_CONFIG_DATA_FAST_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_FAST_8
   #undef CalUT_START_SEC_CONFIG_DATA_FAST_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_FAST_8
   #undef CalUT_STOP_SEC_CONFIG_DATA_FAST_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_FAST_16
   #undef CalUT_START_SEC_CONFIG_DATA_FAST_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_FAST_16
   #undef CalUT_STOP_SEC_CONFIG_DATA_FAST_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_FAST_32
   #undef CalUT_START_SEC_CONFIG_DATA_FAST_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_FAST_32
   #undef CalUT_STOP_SEC_CONFIG_DATA_FAST_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
   #undef CalUT_START_SEC_CONFIG_DATA_FAST_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONFIG_DATA_FAST_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
   #undef CalUT_START_SEC_CONFIG_DATA_SLOW_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
   #undef CalUT_STOP_SEC_CONFIG_DATA_SLOW_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_SLOW_8
   #undef CalUT_START_SEC_CONFIG_DATA_SLOW_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_SLOW_8
   #undef CalUT_STOP_SEC_CONFIG_DATA_SLOW_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_SLOW_16
   #undef CalUT_START_SEC_CONFIG_DATA_SLOW_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_SLOW_16
   #undef CalUT_STOP_SEC_CONFIG_DATA_SLOW_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_SLOW_32
   #undef CalUT_START_SEC_CONFIG_DATA_SLOW_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_SLOW_32
   #undef CalUT_STOP_SEC_CONFIG_DATA_SLOW_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
   #undef CalUT_START_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONFIG_DATA_SLOW_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_8
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_8
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_16
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_16
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_32
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_32
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_8
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_8
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_16
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_16
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_32
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_32
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #undef CalUT_START_SEC_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONFIG_DATA_POSTBUILD_HEADER_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_FAST_BOOLEAN
   #undef CalUT_START_SEC_CONST_FAST_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_FAST_BOOLEAN
   #undef CalUT_STOP_SEC_CONST_FAST_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_FAST_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_FAST_8
   #undef CalUT_START_SEC_CONST_FAST_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_FAST_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_FAST_8
   #undef CalUT_STOP_SEC_CONST_FAST_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_FAST_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_FAST_16
   #undef CalUT_START_SEC_CONST_FAST_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_FAST_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_FAST_16
   #undef CalUT_STOP_SEC_CONST_FAST_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_FAST_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_FAST_32
   #undef CalUT_START_SEC_CONST_FAST_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_FAST_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_FAST_32
   #undef CalUT_STOP_SEC_CONST_FAST_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_FAST_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_FAST_UNSPECIFIED
   #undef CalUT_START_SEC_CONST_FAST_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_FAST_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONST_FAST_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_FAST_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SLOW_BOOLEAN
   #undef CalUT_START_SEC_CONST_SLOW_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SLOW_BOOLEAN
   #undef CalUT_STOP_SEC_CONST_SLOW_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SLOW_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SLOW_8
   #undef CalUT_START_SEC_CONST_SLOW_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SLOW_8
   #undef CalUT_STOP_SEC_CONST_SLOW_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SLOW_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SLOW_16
   #undef CalUT_START_SEC_CONST_SLOW_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SLOW_16
   #undef CalUT_STOP_SEC_CONST_SLOW_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SLOW_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SLOW_32
   #undef CalUT_START_SEC_CONST_SLOW_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SLOW_32
   #undef CalUT_STOP_SEC_CONST_SLOW_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SLOW_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SLOW_UNSPECIFIED
   #undef CalUT_START_SEC_CONST_SLOW_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SLOW_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONST_SLOW_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SLOW_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #undef CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #undef CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #undef CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #undef CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #undef CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #undef CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #undef CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #undef CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #undef CalUT_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #undef CalUT_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #undef CalUT_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_POSTBUILD_8
   #undef CalUT_START_SEC_VAR_CLEARED_POSTBUILD_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_8
   #undef CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_POSTBUILD_16
   #undef CalUT_START_SEC_VAR_CLEARED_POSTBUILD_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_16
   #undef CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_POSTBUILD_32
   #undef CalUT_START_SEC_VAR_CLEARED_POSTBUILD_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_32
   #undef CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_POSTBUILD_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_FAST_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_FAST_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_INIT_8
   #undef CalUT_START_SEC_VAR_FAST_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_INIT_8
   #undef CalUT_STOP_SEC_VAR_FAST_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_INIT_16
   #undef CalUT_START_SEC_VAR_FAST_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_INIT_16
   #undef CalUT_STOP_SEC_VAR_FAST_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_INIT_32
   #undef CalUT_START_SEC_VAR_FAST_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_INIT_32
   #undef CalUT_STOP_SEC_VAR_FAST_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_FAST_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_FAST_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_FAST_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_CLEARED_8
   #undef CalUT_START_SEC_VAR_FAST_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_FAST_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_CLEARED_16
   #undef CalUT_START_SEC_VAR_FAST_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_FAST_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_CLEARED_32
   #undef CalUT_START_SEC_VAR_FAST_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_FAST_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_FAST_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_INIT_BOOLEAN
   #undef CalUT_START_SEC_VAR_SLOW_INIT_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SLOW_INIT_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_INIT_8
   #undef CalUT_START_SEC_VAR_SLOW_INIT_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_INIT_8
   #undef CalUT_STOP_SEC_VAR_SLOW_INIT_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_INIT_16
   #undef CalUT_START_SEC_VAR_SLOW_INIT_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_INIT_16
   #undef CalUT_STOP_SEC_VAR_SLOW_INIT_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_INIT_32
   #undef CalUT_START_SEC_VAR_SLOW_INIT_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_INIT_32
   #undef CalUT_STOP_SEC_VAR_SLOW_INIT_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SLOW_INIT_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SLOW_INIT_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_INIT_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_SLOW_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SLOW_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_CLEARED_8
   #undef CalUT_START_SEC_VAR_SLOW_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_SLOW_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_CLEARED_16
   #undef CalUT_START_SEC_VAR_SLOW_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_SLOW_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_CLEARED_32
   #undef CalUT_START_SEC_VAR_SLOW_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_SLOW_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SLOW_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_8
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_16
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_32
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_START_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #undef CalUT_STOP_SEC_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_VAR_SLOW_POWER_ON_CLEARED_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_START_SEC_HSM_SHARED_VAR_BOOLEAN
   #undef CalUT_START_SEC_HSM_SHARED_VAR_BOOLEAN
   #define ASW_START_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_HSM_SHARED_VAR_BOOLEAN
   #undef CalUT_STOP_SEC_HSM_SHARED_VAR_BOOLEAN
   #define ASW_STOP_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_BOOLEAN
   #include "MemMap.h"
#elif defined CalUT_START_SEC_HSM_SHARED_VAR_8
   #undef CalUT_START_SEC_HSM_SHARED_VAR_8
   #define ASW_START_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_8
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_HSM_SHARED_VAR_8
   #undef CalUT_STOP_SEC_HSM_SHARED_VAR_8
   #define ASW_STOP_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_8
   #include "MemMap.h"
#elif defined CalUT_START_SEC_HSM_SHARED_VAR_16
   #undef CalUT_START_SEC_HSM_SHARED_VAR_16
   #define ASW_START_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_16
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_HSM_SHARED_VAR_16
   #undef CalUT_STOP_SEC_HSM_SHARED_VAR_16
   #define ASW_STOP_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_16
   #include "MemMap.h"
#elif defined CalUT_START_SEC_HSM_SHARED_VAR_32
   #undef CalUT_START_SEC_HSM_SHARED_VAR_32
   #define ASW_START_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_32
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_HSM_SHARED_VAR_32
   #undef CalUT_STOP_SEC_HSM_SHARED_VAR_32
   #define ASW_STOP_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_32
   #include "MemMap.h"
#elif defined CalUT_START_SEC_HSM_SHARED_VAR_UNSPECIFIED
   #undef CalUT_START_SEC_HSM_SHARED_VAR_UNSPECIFIED
   #define ASW_START_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_UNSPECIFIED
   #include "MemMap.h"
#elif defined CalUT_STOP_SEC_HSM_SHARED_VAR_UNSPECIFIED
   #undef CalUT_STOP_SEC_HSM_SHARED_VAR_UNSPECIFIED
   #define ASW_STOP_SEC_EcucPartition_AppCore_HSM_SHARED_VAR_UNSPECIFIED
   #include "MemMap.h"

#else
    #error "CalUT_MemMap.h, memmap section unconfigured"
#endif

/*
**********************************************************************************************************************
* End of the file
**********************************************************************************************************************
*/
