/*----------------------------------------------------------------------------*/
/*
 * File: Os_MemMap.h
 * Generated by: TAN9SGH
 * Version: ETAS Cobra 2.0
 * on: 2022/11/06 14:17
*/
/*----------------------------------------------------------------------------*/

#if defined (NOT_DEFINED)

#elif defined (OS_START_SEC_CALLOUT_CODE)
   #undef      OS_START_SEC_CALLOUT_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CALLOUT_CODE")
#elif defined (OS_STOP_SEC_CALLOUT_CODE)
   #undef      OS_STOP_SEC_CALLOUT_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_APPL_CODE)
   #undef      OS_START_SEC_APPL_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_APPL_CODE")
#elif defined (OS_STOP_SEC_APPL_CODE)
   #undef      OS_STOP_SEC_APPL_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_CODE)
   #undef      OS_START_SEC_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE")
#elif defined (OS_STOP_SEC_CODE)
   #undef      OS_STOP_SEC_CODE
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_VAR_NO_INIT_UNSPECIFIED)
   #undef      OS_START_SEC_VAR_NO_INIT_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION(".OS_VAR_NO_INIT_UNSPECIFIED")
#elif defined (OS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED)
   #undef      OS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION()
#elif defined (OS_START_SEC_CODE_FAST)
   #undef      OS_START_SEC_CODE_FAST
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE_FAST")
#elif defined (OS_STOP_SEC_CODE_FAST)
   #undef      OS_STOP_SEC_CODE_FAST
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_CONST_FAST_UNSPECIFIED)
   #undef      OS_START_SEC_CONST_FAST_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION(".OS_CONST_FAST_UNSPECIFIED")
#elif defined (OS_STOP_SEC_CONST_FAST_UNSPECIFIED)
   #undef      OS_STOP_SEC_CONST_FAST_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION()
#elif defined (OS_START_SEC_CONST_UNSPECIFIED)
   #undef      OS_START_SEC_CONST_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION(".OS_CONST_UNSPECIFIED")
#elif defined (OS_STOP_SEC_CONST_UNSPECIFIED)
   #undef      OS_STOP_SEC_CONST_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION()
#elif defined (OS_START_SEC_VAR_CLEARED_UNSPECIFIED)
   #undef      OS_START_SEC_VAR_CLEARED_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION(".OS_VAR_CLEARED_UNSPECIFIED")
#elif defined (OS_STOP_SEC_VAR_CLEARED_UNSPECIFIED)
   #undef      OS_STOP_SEC_VAR_CLEARED_UNSPECIFIED
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION()
#elif defined (OS_START_SEC_CODE_CORE0_LOCAL)
   #undef      OS_START_SEC_CODE_CORE0_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE_CORE0_LOCAL")
#elif defined (OS_STOP_SEC_CODE_CORE0_LOCAL)
   #undef      OS_STOP_SEC_CODE_CORE0_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_CODE_CORE1_LOCAL)
   #undef      OS_START_SEC_CODE_CORE1_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE_CORE1_LOCAL")
#elif defined (OS_STOP_SEC_CODE_CORE1_LOCAL)
   #undef      OS_STOP_SEC_CODE_CORE1_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_CODE_CORE2_LOCAL)
   #undef      OS_START_SEC_CODE_CORE2_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE_CORE2_LOCAL")
#elif defined (OS_STOP_SEC_CODE_CORE2_LOCAL)
   #undef      OS_STOP_SEC_CODE_CORE2_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_CODE_CORE3_LOCAL)
   #undef      OS_START_SEC_CODE_CORE3_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_CODE_CORE3_LOCAL")
#elif defined (OS_STOP_SEC_CODE_CORE3_LOCAL)
   #undef      OS_STOP_SEC_CODE_CORE3_LOCAL
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()
#elif defined (OS_START_SEC_VAR_TRACE)
   #undef      OS_START_SEC_VAR_TRACE
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION(".OS_VAR_TRACE")
#elif defined (OS_STOP_SEC_VAR_TRACE)
   #undef      OS_STOP_SEC_VAR_TRACE
  //ETAS BIP Porting TODO #pragma SET_DATA_SECTION()
#elif defined (OS_START_SEC_VECTORS)
   #undef      OS_START_SEC_VECTORS
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION(".OS_VECTORS")
#elif defined (OS_STOP_SEC_VECTORS)
   #undef      OS_STOP_SEC_VECTORS
  //ETAS BIP Porting TODO #pragma SET_CODE_SECTION()

#else
  // #error No section in Os_MemMap was matched //zco7sgh
#endif

/*** End of file **************************************************************/
