/*
 * File: Rte_MemMap.h
 * Generated by: TAN9SGH
 * Version: ETAS Cobra 2.0
 * on: 2022/12/29 14:29 
 * This is a template file. It defines integration functions necessary to complete RTA-BSW.
 * The integrator must complete the templates before deploying software containing functions defined in this file.
 * Once templates have been completed, the integrator should delete the #error line.
 * Note: The integrator is responsible for updates made to this file.
 *
 * To remove the following error define the macro NOT_READY_FOR_TESTING_OR_DEPLOYMENT with a compiler option (e.g. -D NOT_READY_FOR_TESTING_OR_DEPLOYMENT)
 * The removal of the error only allows the user to proceed with the building phase
 */

#ifndef NOT_READY_FOR_TESTING_OR_DEPLOYMENT
//#error The content of this file is a template which provides empty stubs. The content of this file must be completed by the integrator accordingly to project specific requirements
#else
//#warning The content of this file is a template which provides empty stubs. The content of this file must be completed by the integrator accordingly to project specific requirements
#endif /* NOT_READY_FOR_TESTING_OR_DEPLOYMENT */
#if defined (RTE_OSTASK_SYSCORE_BSWBG_1MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSWBG_1MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSWBG_1MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSWBG_1MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_APPCORE_BSW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_APPCORE_BSW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_AppCore_CODE
#elif defined (RTE_OSTASK_APPCORE_BSW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_APPCORE_BSW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_AppCore_CODE
#elif defined (RTE_OSTASK_COMCORE_BSW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_COMCORE_BSW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_ComCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_CODE
#elif defined (RTE_OSTASK_COMCORE_BSW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_COMCORE_BSW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_ComCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_CODE
#elif defined (RTE_EXT_START_SEC_CODE)
   #undef      RTE_EXT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_EXT_STOP_SEC_CODE)
   #undef      RTE_EXT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_LIB_START_SEC_CODE)
   #undef      RTE_LIB_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_LIB_STOP_SEC_CODE)
   #undef      RTE_LIB_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SYS_START_SEC_CODE)
   #undef      RTE_SYS_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SYS_STOP_SEC_CODE)
   #undef      RTE_SYS_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_BSWM_START_SEC_CODE)
   #undef      RTE_BSWM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_BSWM_STOP_SEC_CODE)
   #undef      RTE_BSWM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_DCM_START_SEC_CODE)
   #undef      RTE_DCM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_DCM_STOP_SEC_CODE)
   #undef      RTE_DCM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_WDGM_START_SEC_CODE)
   #undef      RTE_WDGM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_WDGM_STOP_SEC_CODE)
   #undef      RTE_WDGM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_CALUT_START_SEC_CODE)
   #undef      RTE_CALUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_CALUT_STOP_SEC_CODE)
   #undef      RTE_CALUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_COMM_START_SEC_CODE)
   #undef      RTE_COMM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_COMM_STOP_SEC_CODE)
   #undef      RTE_COMM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_DEM_START_SEC_CODE)
   #undef      RTE_DEM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_DEM_STOP_SEC_CODE)
   #undef      RTE_DEM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_DIAGUT_START_SEC_CODE)
   #undef      RTE_DIAGUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_DIAGUT_STOP_SEC_CODE)
   #undef      RTE_DIAGUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_EXEMGRUT_START_SEC_CODE)
   #undef      RTE_EXEMGRUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_EXEMGRUT_STOP_SEC_CODE)
   #undef      RTE_EXEMGRUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_INP_SWC_START_SEC_CODE)
   #undef      RTE_INP_SWC_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_INP_SWC_STOP_SEC_CODE)
   #undef      RTE_INP_SWC_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NMUT_START_SEC_CODE)
   #undef      RTE_NMUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NMUT_STOP_SEC_CODE)
   #undef      RTE_NMUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVBLOCK_START_SEC_CODE)
   #undef      RTE_NVBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_START_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_START_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_START_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_START_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREATSHUTDOWNBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_START_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STORECYCLICBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_START_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_STOP_SEC_CODE)
   #undef      RTE_NVM_NVBLOCK_NVBLOCKDESCRIPTOR_STOREIMMEDIATEBLOCK_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_NVMUT_START_SEC_CODE)
   #undef      RTE_NVMUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_NVMUT_STOP_SEC_CODE)
   #undef      RTE_NVMUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_OUTP_SWC_START_SEC_CODE)
   #undef      RTE_OUTP_SWC_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_OUTP_SWC_STOP_SEC_CODE)
   #undef      RTE_OUTP_SWC_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_TSTM_START_SEC_CODE)
   #undef      RTE_TSTM_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_TSTM_STOP_SEC_CODE)
   #undef      RTE_TSTM_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_WDGMUT_START_SEC_CODE)
   #undef      RTE_WDGMUT_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_WDGMUT_STOP_SEC_CODE)
   #undef      RTE_WDGMUT_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREATSHUTDOWNNVBLOCK_START_SEC_VAR_CLEARED_8)
   #undef      RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREATSHUTDOWNNVBLOCK_START_SEC_VAR_CLEARED_8
   #define RTE_START_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_8
#elif defined (RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREATSHUTDOWNNVBLOCK_STOP_SEC_VAR_CLEARED_8)
   #undef      RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREATSHUTDOWNNVBLOCK_STOP_SEC_VAR_CLEARED_8
   #define RTE_STOP_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_8
#elif defined (RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREIMMEDIATENVBLOCK_START_SEC_VAR_CLEARED_8)
   #undef      RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREIMMEDIATENVBLOCK_START_SEC_VAR_CLEARED_8
   #define RTE_START_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_8
#elif defined (RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREIMMEDIATENVBLOCK_STOP_SEC_VAR_CLEARED_8)
   #undef      RTE_AF_CPT_NVBLOCK_DRE_NVBLOCK_STOREIMMEDIATENVBLOCK_STOP_SEC_VAR_CLEARED_8
   #define RTE_STOP_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_8
#elif defined (RTE_START_SEC_EcucPartition_AppCore_VAR_CLEARED_32)
   #undef      RTE_START_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #define RTE_START_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_AppCore_VAR_CLEARED_32
#elif defined (RTE_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_32)
   #undef      RTE_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #define RTE_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_AppCore_VAR_CLEARED_32
#elif defined (RTE_START_SEC_VAR_CLEARED_8)
   #undef      RTE_START_SEC_VAR_CLEARED_8
   #define RTE_START_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_8
#elif defined (RTE_STOP_SEC_VAR_CLEARED_8)
   #undef      RTE_STOP_SEC_VAR_CLEARED_8
   #define RTE_STOP_SEC_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_8
#elif defined (RTE_ECUCPARTITION_COMCORE_START_SEC_VAR_CLEARED_16)
   #undef      RTE_ECUCPARTITION_COMCORE_START_SEC_VAR_CLEARED_16
   #define RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16
#elif defined (RTE_ECUCPARTITION_COMCORE_STOP_SEC_VAR_CLEARED_16)
   #undef      RTE_ECUCPARTITION_COMCORE_STOP_SEC_VAR_CLEARED_16
   #define RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16
#elif defined (RTE_START_SEC_VAR_INIT_UNSPECIFIED)
   #undef      RTE_START_SEC_VAR_INIT_UNSPECIFIED
   #define RTE_START_SEC_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_INIT_UNSPECIFIED
#elif defined (RTE_STOP_SEC_VAR_INIT_UNSPECIFIED)
   #undef      RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
   #define RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
#elif defined (RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8)
   #undef      RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #define RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8)
   #undef      RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #define RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (RTE_START_SEC_VAR_INIT_8)
   #undef      RTE_START_SEC_VAR_INIT_8
   #define RTE_START_SEC_VAR_INIT_8
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_INIT_8
#elif defined (RTE_STOP_SEC_VAR_INIT_8)
   #undef      RTE_STOP_SEC_VAR_INIT_8
   #define RTE_STOP_SEC_VAR_INIT_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_INIT_8
#elif defined (RTE_ECUCPARTITION_SYSCORE_START_SEC_VAR_CLEARED_8)
   #undef      RTE_ECUCPARTITION_SYSCORE_START_SEC_VAR_CLEARED_8
   #define RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (RTE_ECUCPARTITION_SYSCORE_STOP_SEC_VAR_CLEARED_8)
   #undef      RTE_ECUCPARTITION_SYSCORE_STOP_SEC_VAR_CLEARED_8
   #define RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_8
#elif defined (RTE_ECUCPARTITION_SYSCORE_START_SEC_VAR_INIT_8)
   #undef      RTE_ECUCPARTITION_SYSCORE_START_SEC_VAR_INIT_8
   #define RTE_START_SEC_EcucPartition_SysCore_VAR_INIT_8
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_VAR_INIT_8
#elif defined (RTE_ECUCPARTITION_SYSCORE_STOP_SEC_VAR_INIT_8)
   #undef      RTE_ECUCPARTITION_SYSCORE_STOP_SEC_VAR_INIT_8
   #define RTE_STOP_SEC_EcucPartition_SysCore_VAR_INIT_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_VAR_INIT_8
#elif defined (RTE_START_SEC_VAR_CLEARED_BOOLEAN)
   #undef      RTE_START_SEC_VAR_CLEARED_BOOLEAN
   #define RTE_START_SEC_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_BOOLEAN
#elif defined (RTE_STOP_SEC_VAR_CLEARED_BOOLEAN)
   #undef      RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
   #define RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_BOOLEAN
#elif defined (RTE_START_SEC_VAR_CLEARED_16)
   #undef      RTE_START_SEC_VAR_CLEARED_16
   #define RTE_START_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_16
#elif defined (RTE_STOP_SEC_VAR_CLEARED_16)
   #undef      RTE_STOP_SEC_VAR_CLEARED_16
   #define RTE_STOP_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_16
#elif defined (RTE_START_SEC_VAR_CLEARED_32)
   #undef      RTE_START_SEC_VAR_CLEARED_32
   #define RTE_START_SEC_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_32
#elif defined (RTE_STOP_SEC_VAR_CLEARED_32)
   #undef      RTE_STOP_SEC_VAR_CLEARED_32
   #define RTE_STOP_SEC_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_32
#elif defined (RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN)
   #undef      RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #define RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
#elif defined (RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN)
   #undef      RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #define RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_BOOLEAN
#elif defined (RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32)
   #undef      RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #define RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_VAR_CLEARED_32
#elif defined (RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32)
   #undef      RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #define RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_VAR_CLEARED_32
#elif defined (RTE_START_SEC_CONST_BOOLEAN)
   #undef      RTE_START_SEC_CONST_BOOLEAN
   #define RTE_START_SEC_CONST_BOOLEAN
   #include "MemMap.h"
   #undef RTE_START_SEC_CONST_BOOLEAN
#elif defined (RTE_STOP_SEC_CONST_BOOLEAN)
   #undef      RTE_STOP_SEC_CONST_BOOLEAN
   #define RTE_STOP_SEC_CONST_BOOLEAN
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CONST_BOOLEAN
#elif defined (RTE_START_SEC_CONST_8)
   #undef      RTE_START_SEC_CONST_8
   #define RTE_START_SEC_CONST_8
   #include "MemMap.h"
   #undef RTE_START_SEC_CONST_8
#elif defined (RTE_STOP_SEC_CONST_8)
   #undef      RTE_STOP_SEC_CONST_8
   #define RTE_STOP_SEC_CONST_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CONST_8
#elif defined (RTE_START_SEC_CONST_32)
   #undef      RTE_START_SEC_CONST_32
   #define RTE_START_SEC_CONST_32
   #include "MemMap.h"
   #undef RTE_START_SEC_CONST_32
#elif defined (RTE_STOP_SEC_CONST_32)
   #undef      RTE_STOP_SEC_CONST_32
   #define RTE_STOP_SEC_CONST_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CONST_32
#elif defined (RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN)
   #undef      RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
   #define RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
#elif defined (RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN)
   #undef      RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
   #define RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_BOOLEAN
#elif defined (RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16)
   #undef      RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #define RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_16
#elif defined (RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16)
   #undef      RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #define RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_16
#elif defined (RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_8)
   #undef      RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_8
   #define RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_VAR_CLEARED_8
#elif defined (RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_8)
   #undef      RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_8
   #define RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_8
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_VAR_CLEARED_8
#elif defined (RTE_START_SEC_CONST_UNSPECIFIED)
   #undef      RTE_START_SEC_CONST_UNSPECIFIED
   #define RTE_START_SEC_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_START_SEC_CONST_UNSPECIFIED
#elif defined (RTE_STOP_SEC_CONST_UNSPECIFIED)
   #undef      RTE_STOP_SEC_CONST_UNSPECIFIED
   #define RTE_STOP_SEC_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CONST_UNSPECIFIED
#elif defined (RTE_START_SEC_EcucPartition_AppCore_CALPRM_32)
   #undef      RTE_START_SEC_EcucPartition_AppCore_CALPRM_32
   #define RTE_START_SEC_EcucPartition_AppCore_CALPRM_32
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_AppCore_CALPRM_32
#elif defined (RTE_STOP_SEC_EcucPartition_AppCore_CALPRM_32)
   #undef      RTE_STOP_SEC_EcucPartition_AppCore_CALPRM_32
   #define RTE_STOP_SEC_EcucPartition_AppCore_CALPRM_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_AppCore_CALPRM_32
#elif defined (RTE_START_SEC_CALPRM_32)
   #undef      RTE_START_SEC_CALPRM_32
   #define RTE_START_SEC_CALPRM_32
   #include "MemMap.h"
   #undef RTE_START_SEC_CALPRM_32
#elif defined (RTE_STOP_SEC_CALPRM_32)
   #undef      RTE_STOP_SEC_CALPRM_32
   #define RTE_STOP_SEC_CALPRM_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CALPRM_32
#elif defined (RTE_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED)
   #undef      RTE_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #define RTE_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
#elif defined (RTE_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED)
   #undef      RTE_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #define RTE_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CONST_UNSPECIFIED
#elif defined (RTE_START_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED)
   #undef      RTE_START_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #define RTE_START_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
#elif defined (RTE_STOP_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED)
   #undef      RTE_STOP_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #define RTE_STOP_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_AppCore_CONST_UNSPECIFIED
#elif defined (RTE_START_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED)
   #undef      RTE_START_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
   #define RTE_START_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
#elif defined (RTE_STOP_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED)
   #undef      RTE_STOP_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
   #define RTE_STOP_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_CONST_UNSPECIFIED
#elif defined (RTE_SIG_S_ETAS01_SIG00_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG00_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG00_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG00_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG01_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG01_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG01_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG01_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG02_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG02_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG02_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG02_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG03_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG03_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG03_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG03_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG04_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG04_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG04_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG04_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG05_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG05_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG05_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG05_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG06_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG06_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG06_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG06_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG07_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG07_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG07_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG07_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG08_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG08_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS01_SIG08_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS01_SIG08_COMRX_0X81_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS02_SIG09_COMRX_0X261_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS02_SIG09_COMRX_0X261_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS02_SIG09_COMRX_0X261_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS02_SIG09_COMRX_0X261_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG34_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG34_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG34_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG34_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG35_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG35_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG35_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG35_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG36_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG36_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG36_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG36_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG37_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG37_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG37_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG37_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG38_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG38_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG38_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG38_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG39_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG39_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG39_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG39_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG40_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG40_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG40_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG40_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG41_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG41_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_SIG_S_ETAS06_SIG41_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE)
   #undef      RTE_SIG_S_ETAS06_SIG41_COMRX_0X456_CAN_NETWORK_ETAS_CHANNEL_CAN_RX_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#elif defined (RTE_OSTASK_APPCORE_ASW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_APPCORE_ASW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_AppCore_CODE
#elif defined (RTE_OSTASK_APPCORE_ASW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_APPCORE_ASW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_AppCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_AppCore_CODE
#elif defined (RTE_OSTASK_COMCORE_ASW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_COMCORE_ASW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_ComCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_ComCore_CODE
#elif defined (RTE_OSTASK_COMCORE_ASW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_COMCORE_ASW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_ComCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_ComCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_100MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_100MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_100MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_100MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_50MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_50MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_ASW_50MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_ASW_50MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_10MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_10MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_10MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_10MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_1MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_1MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_1MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_1MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_SWCREQUEST_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_SWCREQUEST_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSW_SWCREQUEST_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSW_SWCREQUEST_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSWBG_100MS_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSWBG_100MS_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_BSWBG_100MS_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_BSWBG_100MS_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_DRE_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_DRE_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_DRE_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_DRE_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_STARTUP_START_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_STARTUP_START_SEC_CODE
   #define RTE_START_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_OSTASK_SYSCORE_STARTUP_STOP_SEC_CODE)
   #undef      RTE_OSTASK_SYSCORE_STARTUP_STOP_SEC_CODE
   #define RTE_STOP_SEC_EcucPartition_SysCore_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_EcucPartition_SysCore_CODE
#elif defined (RTE_SYS_START_SEC_VAR_CLEARED_32)
   #undef      RTE_SYS_START_SEC_VAR_CLEARED_32
   #define RTE_START_SEC_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_32
#elif defined (RTE_SYS_STOP_SEC_VAR_CLEARED_32)
   #undef      RTE_SYS_STOP_SEC_VAR_CLEARED_32
   #define RTE_STOP_SEC_VAR_CLEARED_32
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_32
#elif defined (RTE_OSAPP_APPCORE_START_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_APPCORE_START_SEC_VAR_CLEARED_16
   #define RTE_START_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_16
#elif defined (RTE_OSAPP_APPCORE_STOP_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_APPCORE_STOP_SEC_VAR_CLEARED_16
   #define RTE_STOP_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_16
#elif defined (RTE_OSAPP_COMCORE_START_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_COMCORE_START_SEC_VAR_CLEARED_16
   #define RTE_START_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_16
#elif defined (RTE_OSAPP_COMCORE_STOP_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_COMCORE_STOP_SEC_VAR_CLEARED_16
   #define RTE_STOP_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_16
#elif defined (RTE_OSAPP_SYSCORE_START_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_SYSCORE_START_SEC_VAR_CLEARED_16
   #define RTE_START_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_START_SEC_VAR_CLEARED_16
#elif defined (RTE_OSAPP_SYSCORE_STOP_SEC_VAR_CLEARED_16)
   #undef      RTE_OSAPP_SYSCORE_STOP_SEC_VAR_CLEARED_16
   #define RTE_STOP_SEC_VAR_CLEARED_16
   #include "MemMap.h"
   #undef RTE_STOP_SEC_VAR_CLEARED_16
#elif defined (RTE_MAIN_START_SEC_CODE)
   #undef      RTE_MAIN_START_SEC_CODE
   #define RTE_START_SEC_CODE
   #include "MemMap.h"
   #undef RTE_START_SEC_CODE
#elif defined (RTE_MAIN_STOP_SEC_CODE)
   #undef      RTE_MAIN_STOP_SEC_CODE
   #define RTE_STOP_SEC_CODE
   #include "MemMap.h"
   #undef RTE_STOP_SEC_CODE
#else
    #error "Rte_MemMap.h, memmap section unconfigured"
#endif


/*
 **********************************************************************************************************************
 * End of the file
 **********************************************************************************************************************
 */
